# Generated by Django 6.0.6 on 2026-07-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
