# Generated by Django 6.0.6 on 2026-07-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
