# Generated by Django 6.0.6 on 2026-07-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_rename_update_at_leaverequest_updated_at'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE leaves_leaverequest
            ALTER COLUMN is_deleted TYPE boolean
            USING CASE
                WHEN is_deleted IS NULL THEN FALSE
                ELSE TRUE
            END;
            """,
            reverse_sql="""
            ALTER TABLE leaves_leaverequest
            ALTER COLUMN is_deleted TYPE timestamp with time zone
            USING NULL;
            """,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
